id: IC9C17D7F
ocr_import_info:
  timestamp: '2023-09-27T04:30:59.562478+00:00'
  batch_id: batch-282c
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-27 06:02:24.072587+00:00
last_modified: 2023-09-27 06:02:24.072593+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS31211
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS31211
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མདོ་སྡེ་ལས་བྱུང་བའི་སྨན་བླའི་ཆོ་ག
  languages:
  - bo
  author: ཀརྨ་པ ༠༨་མི་བསྐྱོད་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.9395972398748746
  ocr_word_median_confidence_index: 0.994950665
bases:
  I8LS31230:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS31230
      total_pages: 505
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS31230.txt
    statistics:
      ocr_word_median_confidence_index: 0.994950665
      ocr_word_mean_confidence_index: 0.9395972398748746
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
